//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int voteId { get; set; }
        public int gamePlacementLeft { get; set; }
        public int gamePlacementRight { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Game Game1 { get; set; }
    }
}
