// <auto-generated />
namespace PetStore_web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class pushing_model1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pushing_model1));
        
        string IMigrationMetadata.Id
        {
            get { return "201403190133278_pushing_model1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
